### ISSUE TITLE
Where are the images?

### ISSUE THREAD

**Issue by pdurbin** [gdcc/ct.gdcc.io#5]
Some feedback from our monthly meeting just now: we should probably more prominently link to https://hub.docker.com/r/gdcc/dataverse

Perhaps this could even be under its own heading, near the top.

**Comment by akio-sone** [comment]
@pdurbin I think Image pages (both base and application) need a section of instruction/command lines for how to spin these image to actually run Dataverse.

**Comment by pdurbin** [comment]
@akio-sone right, good idea. As discussed in [yesterday's meeting](https://harvard.zoom.us/rec/share/Nsm8SZgE05wuziNoGPA9fYNCPoYH1sKqvgS7omn-nclo6qFTsAn-qu-pqF4JnFuZ.joqMRTV6SqSf5gMl), can you please create a dedicated issue for this? A PR would be great too! I can help you with it.
